# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x02\x64\x62\"*\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\"\x1f\n\rReturnMessage\x12\x0e\n\x06status\x18\x01 \x01(\x08\" \n\rDeleteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyMessage\"$\n\tUsersList\x12\x17\n\x05users\x18\x01 \x03(\x0b\x32\x08.db.User2\x93\x01\n\x08\x44\x61tabase\x12&\n\x07PutUser\x12\x08.db.User\x1a\x11.db.ReturnMessage\x12\x32\n\nDeleteUser\x12\x11.db.DeleteRequest\x1a\x11.db.ReturnMessage\x12+\n\x08GetUsers\x12\x10.db.EmptyMessage\x1a\r.db.UsersListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=20
  _USER._serialized_end=62
  _RETURNMESSAGE._serialized_start=64
  _RETURNMESSAGE._serialized_end=95
  _DELETEREQUEST._serialized_start=97
  _DELETEREQUEST._serialized_end=129
  _EMPTYMESSAGE._serialized_start=131
  _EMPTYMESSAGE._serialized_end=145
  _USERSLIST._serialized_start=147
  _USERSLIST._serialized_end=183
  _DATABASE._serialized_start=186
  _DATABASE._serialized_end=333
# @@protoc_insertion_point(module_scope)
